#!/bin/sh

verify() {
    if ./lsfr "$@" debug=1 > lsfr.log; then
        result1=$(wc -l < lsfr.log)
        result2=$(sort -u < lsfr.log | wc -l)

        if [ $result1 -ne $result2 ]; then
            echo "period $result1 != $result2"
        else
            echo "period $result1"
        fi
    fi
}

if [ "$1" = "help" ]; then
    cat << EOF
Usage:
  $0 [<option>=<value>] ...
  $0 [--] [<option>=<value>] ...
EOF
    exit 0
elif [ "$1" = "--" ]; then
    shift
elif [ -n "$1" ]; then
    verify "$@"
    exit 0
fi

size=2
while [ $size -le 64 ]; do
    verify size=$size "$@"
    size=$((size + 1))
done
